from django.urls import path
from .views import (
    SongsListView,
    SongDetailView,
    ArtistsListView,
    ArtistDetailView,
    delete_playlist,
    alter_playlist,
    sendPlaylist,
    create_playlist,
    send_songs,
    # send_song,
    # search,
    modify_playlist,
    likes_manage,
    dlikes_manage,
    send_nationality,
    send_language,
    send_all_artists,
)

urlpatterns = [
    path("delete_playlist/", delete_playlist, name="delete_playlist"),
    path("alter_playlist/", alter_playlist, name="alter_playlist"),
    path("send_playlist/", sendPlaylist, name="send_playlist"),
    path("create_playlist/", create_playlist, name="create_playlist"),
    path("songsview/", SongsListView.as_view(), name="songs-list"),
    path("songsdetails/<int:pk>/", SongDetailView.as_view(), name="song-detail"),
    path("artistsview/", ArtistsListView.as_view(), name="artists-list"),
    path("artistsdetails/<int:pk>/", ArtistDetailView.as_view(), name="artist-detail"),
    path("send_songs/", send_songs, name="send-songs"),
    path("send_nationality/", send_nationality, name="send-nationality"),
    path("send_language/", send_language, name="send-language"),
    path("send_all_artists/", send_all_artists, name="send-all-artists"),
    # path("send_song/", send_song, name="send-song"),
    # path("search/", search, name="search-song"),
    path("modify_playlist/", modify_playlist, name="modify_playlist"),
    path("likes_manage/", likes_manage, name="likes_manage"),
    path("dlikes_manage/", dlikes_manage, name="dlikes_manage"),
    # path("send_user_data/", send_user_data, name="send_user_data"),
]
